name: Redmine
description: |
  Redmine is a flexible project management web application. Written using the Ruby on Rails framework, it is cross-platform and cross-database.
version: 3.3.0-passenger
category: Agile
